Repository cloudcreativity/laravel-json-api, pull requests merged in 2019-06, with the labels that each got.

#361 [Feature] Allow dot notation for soft delete field name
  src/Eloquent/Concerns/SoftDeletesModels.php
Labels: enhancement

#370 [Bugfix] Fix wrong returned methods in validators
  src/Validation/AbstractValidators.php
Labels: bug

#363 [Feature] Add Eloquent adapter scopes
  CHANGELOG.md
  docs/basics/adapters.md
  src/Eloquent/AbstractAdapter.php
  tests/lib/Integration/Eloquent/ScopesTest.php
Labels: feature
